### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gcampedelli** [Smile-SA/magento2-module-map#14]
Hello, 
When I load the map, I get this error in developer or production mode. Do you know how can I solve it. 

![image](https://user-images.githubusercontent.com/7084395/44929276-dba72580-ad30-11e8-83f0-2e18e09508f2.png)

**Comment by delyriand** [comment]
I do not reproduce the error.

How many stores do you have?
Can you give me details about store's information? (address, latitude, longitude for example)

**Comment by gcampedelli** [comment]
Magento 2 Single Store Module
Smile Store Delivery - 2 Stores
Address - Rua Coronel Oscar Porto, 70
-23.570921
-46.649910

**Comment by gcampedelli** [comment]
Turns out that the issue went away. I was checking and there is a mistake in Google Maps concerning the zip code of their on building which is at Coronel Oscar Porto 70. In Google Maps it is declared as 013XX-002 but actually is 040XX-XXX. When I corrected this value and got latitude and longitude from OpenMaps it went away.

**Comment by delyriand** [comment]
@gcampedelli,

I do not reproduce the problem on the latest version of modules. I created a store in São Paulo and the map is displayed correctly.

In your code changes, you have add region management. Maybe it's related to that. Can you delete values in the region and region_id columns in smile_retailer_address table?

I also give you screenshots of my store (front and back - I noticed a problem with the display of the country in front). If you see a different element of your configuration do not hesitate to tell me. 

![retailer_sao_paulo_admin](https://user-images.githubusercontent.com/465524/45087236-7cb52800-b105-11e8-864b-b5cb29062c8f.png)
![retailer_sao_paulo_front_detail](https://user-images.githubusercontent.com/465524/45087238-7d4dbe80-b105-11e8-9ce4-1bfe2c6772cd.png)

**Comment by gcampedelli** [comment]
Hi, thank you for your time. I think that the country displaying in this code as Indonesia has something related with a PR that I applied to this code. I will do both things. First I will remove the PR related to country and then I will apply your suggestion to see if maps display as they should.

**Comment by delyriand** [comment]
it's my fault for country name ...

**Comment by gcampedelli** [comment]
Steps to reproduce
1- Uninstall the module
2-Clear database
3- Reinstall the module (Map, Retailer, StoreLocator, Seller and StoreDelivery)
4- Set ipstack key
5 - Insert 2 Stores

Expected Result
1 - Stores display at mydomain.com/stores

Results
It display no store and no map but we can find the stores address in the generated url

![image](https://user-images.githubusercontent.com/7084395/45114502-8a79a600-b123-11e8-8c2e-51632b56f0bc.png)

**Comment by delyriand** [comment]
And after a cache clean, is the store list still empty?

**Comment by gcampedelli** [comment]
Hi, after cleaning cache, there where 0 stores displaying as well. I tested in all browser. 
Stores displayed after changing Zoom settings from No to Yes in Smile Map Service on backend. But then Uncaught RangeError: Maximum call stack size exceeded came back.

**Comment by delyriand** [comment]
I have :
- install magento 2.2.5
- install retailer modules : `composer require smile/module-store-delivery` (other retailer modules are installed because they are required by that one)

```Package operations: 8 installs, 0 updates, 0 removals
  - Installing igorw/get-in (v1.0.3): Loading from cache
  - Installing egeloen/http-adapter (0.8.0): Loading from cache
  - Installing willdurand/geocoder (v3.3.2): Loading from cache
  - Installing smile/module-seller (1.2.2): Loading from cache
  - Installing smile/module-retailer (1.2.3): Loading from cache
  - Installing smile/module-map (1.1.2): Loading from cache
  - Installing smile/module-store-locator (1.3.2): Loading from cache
  - Installing smile/module-store-delivery (1.1.0): Loading from cache
```
- in last release, we don't have "Ipstack key". The configuration parameter will be present at the next tag
- add 2 sellers with the following latitudes and longitudes:
     - -23.570877, -46.649987
     - -22.907822, -43.190862
- clear magento cache

![sellers](https://user-images.githubusercontent.com/465524/45158219-9e84dc80-b1e3-11e8-8ffa-55927a9db5c5.png)

---

can you send me the JSON present in the source of the page?
- Open source in your brower (Ctrl+U)
- Find  `{"store-locator-search"`
- copy all json and paste it here

**Comment by gcampedelli** [comment]
Hello, 
I did exactly this install using composer. Here we go.  You can try to see it alive at 
https://espressivo.com.br/stores
I get 0 stores at search and this JS error I mentioned before. 
I just left stores disabled for checkout. I will leave it like this for you to see. I get a loop on refresh markers. 

</script><script type="text/x-magento-init">
--
  | {"*" : {"Magento_Ui/js/core/app": {"components":{"store-locator-search":{"component":"smile-storelocator-map","template":"Smile_StoreLocator\/retailer\/search","children":{"geocoder":{"component":"smile-geocoder","searchTitleText":"Find a store :","searchPlaceholderText":"City, Zipcode, Department, ...","searchButtonText":"Pesquisa","provider":"osm","tile_url":"http:\/\/{s}.tile.osm.org\/{z}\/{x}\/{y}.png","direction_url_template":"http:\/\/www.openstreetmap.org\/directions?route={{depend has_origin}}{{var orig_latitude}},{{var orig_longitude}}{{\/depend}};{{var dest_latitude}},{{var dest_longitude}}","country":"BR","locale":"pt_BR","markerIcon":"https:\/\/espressivo.com.br\/static\/frontend\/Meigee\/barbour\/pt_BR\/Smile_Map\/leaflet\/images\/marker-icon.png"},"store-list":{"component":"uiComponent","storeListTemplate":"Smile_StoreLocator\/retailer\/search\/store-list","storeDetailTemplate":"Smile_StoreLocator\/retailer\/search\/store-detail","searchResultsLabel":"%s result(s)","nearbySearchLabel":"%s shop(s) nearby","viewAllLabel":"View all"}},"provider":"osm","markers":[{"id":"1","latitude":"-22.9078","longitude":"-43.1909","name":"Loja 1","address":"Rua Moncorvo Filho, 178, Centro, Rio de Janeiro - RJ, 20211-340, Brasil","url":"https:\/\/espressivo.com.br\/stores\/loja-1","directionUrl":"http:\/\/www.openstreetmap.org\/directions?route=;-22.9078,-43.1909","setStoreData":{"action":"https:\/\/espressivo.com.br\/storelocator\/store\/set\/","data":{"id":"1"}},"contact_mail":"","contact_phone":"","schedule":{"locale":"pt_BR","dateFormat":"YYYY-MM-DD","timeFormat":"HH:mm:ss","closingWarningThresold":60,"calendar":{"2018-09-06":[{"start_time":"11:30","end_time":"12:45"}],"2018-09-07":[{"start_time":"11:15","end_time":"12:30"}],"2018-09-08":[{"start_time":"14:15","end_time":"15:30"}],"2018-09-09":[{"start_time":"08:15","end_time":"09:30"}],"2018-09-10":[{"start_time":"11:45","end_time":"12:45"}],"2018-09-11":[{"start_time":"08:45","end_time":"12:45"}],"2018-09-12":[{"start_time":"14:15","end_time":"15:30"}]},"openingHours":[[{"start_time":"08:15","end_time":"09:30"}],[{"start_time":"11:45","end_time":"12:45"}],[{"start_time":"08:45","end_time":"12:45"}],[{"start_time":"14:15","end_time":"15:30"}],[{"start_time":"11:30","end_time":"12:45"}],[{"start_time":"11:15","end_time":"12:30"}],[{"start_time":"14:15","end_time":"15:30"}]],"specialOpeningHours":[]}},{"id":"2","latitude":"-23.5709","longitude":"-46.65","name":"Loja 2","address":"Rua Coronel Oscar Porto, 70, Para\u00edso, S\u00e3o Paulo - SP, 04003-000, Brasil","url":"https:\/\/espressivo.com.br\/stores\/loja-2","directionUrl":"http:\/\/www.openstreetmap.org\/directions?route=;-23.5709,-46.65","setStoreData":{"action":"https:\/\/espressivo.com.br\/storelocator\/store\/set\/","data":{"id":"2"}},"contact_mail":"","contact_phone":"","schedule":{"locale":"pt_BR","dateFormat":"YYYY-MM-DD","timeFormat":"HH:mm:ss","closingWarningThresold":60,"calendar":{"2018-09-06":[{"start_time":"08:30","end_time":"09:30"}],"2018-09-07":[{"start_time":"11:30","end_time":"12:45"}],"2018-09-08":[{"start_time":"11:15","end_time":"12:30"}],"2018-09-09":[{"start_time":"08:15","end_time":"09:30"}],"2018-09-10":[{"start_time":"08:15","end_time":"09:30"}],"2018-09-11":[{"start_time":"11:30","end_time":"12:30"}],"2018-09-12":[{"start_time":"11:30","end_time":"12:30"}]},"openingHours":[[{"start_time":"08:15","end_time":"09:30"}],[{"start_time":"08:15","end_time":"09:30"}],[{"start_time":"11:30","end_time":"12:30"}],[{"start_time":"11:30","end_time":"12:30"}],[{"start_time":"08:30","end_time":"09:30"}],[{"start_time":"11:30","end_time":"12:45"}],[{"start_time":"11:15","end_time":"12:30"}]],"specialOpeningHours":[]}}],"tile_url":"http:\/\/{s}.tile.osm.org\/{z}\/{x}\/{y}.png","direction_url_template":"http:\/\/www.openstreetmap.org\/directions?route={{depend has_origin}}{{var orig_latitude}},{{var orig_longitude}}{{\/depend}};{{var dest_latitude}},{{var dest_longitude}}","country":"BR","locale":"pt_BR","markerIcon":"https:\/\/espressivo.com.br\/static\/frontend\/Meigee\/barbour\/pt_BR\/Smile_Map\/leaflet\/images\/marker-icon.png"}}} }}
  | </script><script type="text/x-magento-init">
  | {
  | "*": {
  | "Magento_Ui/js/core/app": {
  | "components": {
  | "storage-manager": {
  | "component": "Magento_Catalog/js/storage-manager",
  | "appendTo": "",
  | "storagesConfiguration" :
  | {"recently_viewed_product":{"requestConfig":{"syncUrl":"https:\/\/espressivo.com.br\/catalog\/product\/frontend_action_synchronize\/"},"lifetime":"1000","allowToSendRequest":null},"recently_compared_product":{"requestConfig":{"syncUrl":"https:\/\/espressivo.com.br\/catalog\/product\/frontend_action_synchronize\/"},"lifetime":"1000","allowToSendRequest":null},"product_data_storage":{"updateRequestConfig":{"url":"https:\/\/espressivo.com.br\/rest\/espressivo\/V1\/products-render-info"},"allowToSendRequest":null}} }
  | }
  | }
  | }
  | }

**Comment by delyriand** [comment]
It looks like the css of the store-locator module is not loaded. Try to see why the file "vendor/smile/module-store-locator/view/frontend/web/css/source/_module.less" is not included.
if you are in production mode, do you deploy static files?

**Comment by gcampedelli** [comment]
That solved the issue
