### ISSUE TITLE
Store search function work incorrectly on Shipping page

### ISSUE THREAD

**Issue by oscarsanch** [Smile-SA/magento2-module-map#25]
### Preconditions

Magento Version :  2.3.3 (Commerce)

Module Map Version : 1.1.6 (in addition to store locator extension)

Environment : Production mode

Third party modules : Google Maps

### Steps to reproduce

1. We have available retailer addresses for country Australia
2. Need to add product to cart 
3. go to checkout and to choose shipping method =Deliver my order in store=
4. in popup need to enter postcode in search field
5. click search

### Expected result

1.Need to show all retailers that match postcodes

### Actual result

1.Nothing happen

I think issue in file smile/module-map/view/frontend/web/js/geocoder-provider/google.js

```
Geocoder.prototype.geocode = function (queryText, options, callback) {
    if (geocoder === null && google && google.maps) {
        geocoder = new google.maps.Geocoder();
    } else if (geocoder === null) {
        throw __('Google Maps API is not ready yet.')
    }

    var request = {address: queryText, region: 'FR'};

    geocoder.geocode(request, function(results) {
        results = results.map(this.prepareResult);

        if (options['bounds']) {
            results = results.filter(function(result) { return options['bounds'].contains(result.location); });
        }

        callback(results);
    }.bind(this));
};
```

Where  

 `var request = {address: queryText, region: 'FR'};
`

Why is region available only for France?

**Comment by Fdec** [comment]
Hi @oscarsanch 

Historically this module was made for a French project, that's why. But you can purpose a PR to fix it.
