### ISSUE TITLE
Remove dependency to Schedule and Store Locator

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-map#33]
I spotted many explicit inclusions of high-level objects (shop, schedule, shop status) that should rather be in the store-locator module :)

Maybe the list is not exhaustive.

https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L7
https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L8

https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L66
https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L67

https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L284

https://github.com/Smile-SA/magento2-module-map/blame/master/view/frontend/web/js/map.js#L552

**Comment by Fdec** [comment]
Thanks @romainruaud, I add this in my todolist
