### ISSUE TITLE
No-break spaces breaking JavaScript bundling

### ISSUE THREAD

**Issue by Vedrillan** [Smile-SA/magento2-module-map#4]
A few no-break spaces are present in JavaScript files and corrupt the Magento merged JavaScript file:

![tooltip_139](https://cloud.githubusercontent.com/assets/2758851/23345070/2c5b321a-fc88-11e6-9d11-c6e8a4afe67f.png)

**Comment by Vedrillan** [comment]
Well apparently there are less no-break space in branch 1.1.x than in master, only one was left to fix in 1.1.x.

**Comment by romainruaud** [comment]
Fixed by your PR #5
